<?php

/**
 * Implements hook_menu().
 */
function flexiaccess_options_menu() {

  $items = array();

  $items['admin/config/people/flexiaccess-options'] = array(
    'title' => 'Flexi Access Options',
    'description' => 'Administrator settings for Flexi Access Options.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flexiaccess_options_admin_content'),
    'access arguments' => array('administer flexiaccess options'),
    'file' => 'flexiaccess_options.admin.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
  );

  $items['admin/config/people/flexiaccess/settings'] = array(
    'title' => 'Main settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function flexiaccess_options_form_flexiaccess_page_alter(&$form, &$form_state, $form_id) {
  $usersListType = variable_get('users_list_type', 'select');
  if($usersListType == 'select') {
    $users = entity_load('user');
    $usersList = array();

    foreach($users as $user) {
      if(isset($user->name) && $user->name) {
        $usersList[$user->name] = $user->name;
      }
    }

    $form['acl']['view']['add'] = array(
      '#type' => 'select',
      '#title' => t('Add user'),
      '#options' => $usersList,
    );
  };
}

/**
 * Implements hook_theme_registry_alter().
 */
function flexiaccess_options_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'flexiaccess_options');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

function flexiaccess_options_preprocess_page(&$variables) {    
  $status = drupal_get_http_header("status");  
  if($status == '403 Forbidden') {
    $variables['theme_hook_suggestions'][] = 'page__403';
  }
  if($status == '404 Not Found') {
    $variables['theme_hook_suggestions'][] = 'page__404';
  }
}