<?php

module_load_include('inc', 'bookmark_related_content', 'includes/db');

/**
 * Implements hook_block_info().
 */
function bookmark_related_content_block_info() {
	$blocks['bookmark_related_content'] = array(
		// The name that will appear in the block list.
		'info' => t('Bookmark Related Content'),
		// Default setting.
		'cache' => DRUPAL_CACHE_PER_USER,
	);

	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function bookmark_related_content_block_view($delta = '') {
	$block = array();

	switch ($delta) {
		case 'bookmark_related_content':
			$block['content'] = bookmark_related_content_block_content();
		break;
	}

	return $block;
}

/**
 * Implements hook_theme().
 */
function bookmark_related_content_theme($existing, $type, $theme, $path){
    return array(
        'bookmark_related_content' => array(
            'variables' => array('nodes' => NULL),
            'template' => 'bookmark_related_content', // place you file in 'theme' folder of you module folder
            'path' => drupal_get_path('module', 'bookmark_related_content') .'/templates'
        ),
    );
}

/**
 * Block content callback().
 */
function bookmark_related_content_block_content() {
	$db = new DB();
	$nids = $db->getBookmarksByUID();

	$nodes = array();
	if(!empty($nids)) {
		$nodes = node_load_multiple($nids);
	}

	return theme('bookmark_related_content', array('nodes' => $nodes));
}