<?php

/**
 * Implement hook_menu().
 */
function mck_global_menu() {
  $items['case-study/%'] = [
    'title' => '',
    'page arguments' => [1],
    'page callback' => 'mck_global_case_study',
    'delivery callback' => 'bookmark_new_ajax',
    'access callback' => TRUE,
  ];

  return $items;
}

/**
 * Implements hook_ds_fields_info().
 */
function mck_global_ds_fields_info() {
  $fields['node_operations'] = [
    'title' => t('Case Study Header'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'function' => 'mck_global_case_study_header',
  ];

  $fields['viewer_js'] = [
    'title' => t('Viewer JS PDG'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'function' => 'mck_global_viewer_js',
  ];

  return ['node' => $fields];
}

function mck_global_case_study_header(array $field) {
  $node = $field['entity'];

  // @TODO get the share info

  $info = [
    'nid' => $node->nid,
    'title' => $node->title,
    'case_study' => file_create_url($node->field_case_study[LANGUAGE_NONE][0]['uri']),
    'alias' => drupal_get_path_alias('node/' . $node->nid)
  ];

  $output['case_study_header'] = [
    '#theme' => 'case_study_header',
    '#info' => $info,
  ];

  return render($output);
}

function mck_global_viewer_js(array $field) {
  $node = $field['entity'];
  $filename = $node->field_case_study[LANGUAGE_NONE][0]['filename'];

  return '<iframe class="pdf-iframe" src="' . base_path() . 'ViewerJS/#../system/files/' . $filename . '"></iframe>';
}

/**
 * Implements hook_theme().
 */
function mck_global_theme($existing, $type, $theme, $path) {
  return [
    'case_study_header' => [
      'variables' => ['info' => []],
      'template' => 'case-study-header',
      'path' => drupal_get_path('module', 'mck_global') . '/theme',
    ],
  ];
}

/**
 * Return a case study full view mode in json.
 *
 * @param $nid
 *
 * @return array
 */
function mck_global_case_study($nid) {
  $output = [
    'html' => '',
    'error' => TRUE,
  ];

  if ($nid) {
    $node = node_load($nid);

    $entity_view = entity_view('node', [$node], 'full');
    $item = render($entity_view);

    $output = [
      'html' => $item,
      'error' => FALSE,
    ];
  }

  return $output;
}